# The block that will replace all other blocks looked at
replace-with: "minecraft:bedrock"

# List of blocks that the plugin will NOT change when looked at
ignored-blocks:
  - "minecraft:obsidian"
  - "minecraft:nether_portal"
  - "minecraft:end_portal_frame"
  - "minecraft:end_portal"

# Maximum distance (in blocks) at which a player can look to trigger the change
# Lower this value if you experience performance issues
max-distance: 64
